### ISSUE TITLE
Copyright {yyyy} {name of copyright owner}

### ISSUE THREAD

**Issue by ilius** [roosmaa/blue-app-nano#1]
You are supposed to replace "Copyright {yyyy} {name of copyright owner}" in LICENSE with something like "2018 Mart Roosmaa" :)

https://github.com/roosmaa/blue-app-nano/blob/92b79f4faca229881bcbce7abb4c80df342ae04b/LICENSE#L189

Thanks for the work by the way :+1:

**Comment by roosmaa** [comment]
That file originates from the blue-app-btc repo (from which this project was based on). Guess the per-file copyright notices override this. Anyway, will update the `LICENSE` to include the copyright holders there as well. Thanks for pointing it out :)
