### ISSUE TITLE
use nano_ instead of xrb_

### ISSUE THREAD

**Issue by My1** [roosmaa/blue-app-nano#4]
well title kinda explains itself. when using this applet (in my case with nault) the address of the own account is always shown as xrb instead of nano. for some reason tho the target address of a transaction is shows with nano properly

**Comment by roosmaa** [comment]
Have all the Nano wallets [with Ledger integration] finally migrated off of the `xrb_` prefix? If so, changing the default address prefix would be a simple configuration change here:

https://github.com/roosmaa/ledger-app-nano/blob/255fef9ea9944da568c5ef63c7ee8394a51cc26c/src/coins.c#L16-L18

**Comment by My1** [comment]
honestly no idea (although nanovault is off the table by now), but there's probably no way for the wallet to say whether or not it supports the new prefix I guess.

I think even if not it might be a good idea to at least leave this open as a tracking ticket (and that people see that this has been raised already)

**Comment by Joohansson** [comment]
Yes, nano wallets have fully migrated off xrb for quite some time. I think it should be changed asap.

**Comment by Joohansson** [comment]
@roosmaa Would be nice if this can be done now with all new users rolling in
