### ISSUE TITLE
When confirming a receive-transaction, the Ledger display says "Accept and send"

### ISSUE THREAD

**Issue by Joohansson** [roosmaa/blue-app-nano#6]
Maybe change to just "Accept" if too complicated to detect transaction type.
SEND, RECEIVE, CHANGE

**Comment by My1** [comment]
I think send is less about sending money but sending out the transaction. maybe

**Comment by DarrenAlex** [comment]
The code for that is in [libn_bagl_nanox.c](https://github.com/roosmaa/ledger-app-nano/blob/master/src/libn_bagl_nanox.c)
I suggest making a PR and removing the `and send` text.
