### ISSUE TITLE
Add Nault.cc wallet

### ISSUE THREAD

**Issue by DarrenAlex** [roosmaa/blue-app-nano#9]
Here's the docs: [https://github.com/Nault/Nault/blob/master/README.md](https://github.com/Nault/Nault/blob/master/README.md)

Nault is a code fork of NanoVault and it's newer.

**Comment by Joohansson** [comment]
How have I missed that =) Yeah, the README should be updated to replace nanovault.io since it's no longer working, or at the very least add Nault. Also, update the guide to https://docs.nault.cc/2020/08/04/ledger-guide.html please
